### Register unsecured password
POST http://localhost:3000/register
Content-Type: application/json
Accept: application/json

{
    "username": "farrel",
    "password": "secret"
}

### Register
POST http://localhost:3000/register
Content-Type: application/json
Accept: application/json

{
    "username": "farrel",
    "password": "Rahasia!"
}

### Getting token
POST http://localhost:3000/login
Content-Type: application/json
Accept: application/json

{
    "username": "farrel",
    "password": "Rahasia!"
}

### Admin login
POST http://localhost:3000/login
Content-Type: application/json
Accept: application/json

{
    "username": "admin",
    "password": "test"
}

### Update password
POST http://localhost:3000/reset-password
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhcnJlbCIsImlhdCI6MTcyMDc2ODg0NCwiZXhwIjoxNzIwNzcyNDQ0fQ.XaefN71b7kVqkIiRBB2A7-MkR2NsB4ZgvoZ-ZzO3Y4g
{
    "currentPassword": "Rahasia!",
    "newPassword": "Mysecret!"
}

### Unauthenticated request
GET http://localhost:3000/shops/toyota/revenue
Accept: application/json

### Unauthorized request
GET http://localhost:3000/shops/nike/revenue
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhcnJlbCIsImlhdCI6MTcyMDc2ODI1MywiZXhwIjoxNzIwNzcxODUzfQ.ZcQZXypVbr5iLzMtleBVYwI1fLOCkkomABEXwegTgw4

### Authenticated request
GET http://localhost:3000/shops/toyota/revenue
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhcnJlbCIsImlhdCI6MTcyMDc2ODg0NCwiZXhwIjoxNzIwNzcyNDQ0fQ.XaefN71b7kVqkIiRBB2A7-MkR2NsB4ZgvoZ-ZzO3Y4g

### Host approved request
POST http://localhost:3000/api/host/approve_booking/1
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhcnJlbCIsImlhdCI6MTcyMDc3OTIxOSwiZXhwIjoxNzIwNzgyODE5fQ.FeYXB13StVJ9hWfzfThMWHO1JQLfxtZUPQH3JYvkU9o

{
    "approved": true,
    "comment": "Approved",
    "price": 10000000
}

### Testing sms code
POST http://localhost:3000/sms_forgot_password

### Invite user
POST http://localhost:3000/api/invites/new
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIwNzkyMDk4LCJleHAiOjE3MjA3OTU2OTh9.5JIBFfprHgJUvvFJ2C9CERi7Q7FYZwURxSy6uTe4nSk

{
    "username": "budi"
}

### Get all users
GET http://localhost:3000/api/users/all
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIwNzkyMDk4LCJleHAiOjE3MjA3OTU2OTh9.5JIBFfprHgJUvvFJ2C9CERi7Q7FYZwURxSy6uTe4nSk
